backend:
  name: github
  repo: daniaalnahdi/content-labeling
  commit_messages:
    create: Create {{collection}}
    update: Update {{collection}}
    delete: Delete {{collection}}
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

media_folder: static/assets
public_folder: assets

collections:
  - name: platform
    label: Platform
    folder: platform
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
