backend:
  name: github
  repo: daniaalnahdi/content-labeling

media_folder: static/assets
public_folder: assets

collections:
  - name: platform
    label: Platorm
    folder: platform
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
