backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: Create {{collection}}
    update: Update {{collection}}
    delete: Delete {{collection}}
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”

media_folder: static/assets
public_folder: assets

collections:
  - name: platform
    label: Platform
    folder: src/content/platforms
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: spreadsheet, label: Spreadsheet, widget: string}
